name: Unit test for MediaWikiApi core
on:
  push:
    branches: [master, dev, actions]
  pull_request_review:
    types: [submitted]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || (github.event_name == 'pull_request_review' && github.event.review.state == 'APPROVED')

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node Version
        uses: actions/setup-node@v2

      - name: Init deps
        run: |
          npm i -g pnpm
          pnpm i

      - name: Build
        run: |
          pnpm build

      - name: Run test
        env:
          MOEGIRL_API_USER_AGENT: ${{ secrets.MOEGIRL_API_USER_AGENT }}
          MOEGIRL_USERNAME: ${{ secrets.MOEGIRL_USERNAME }}
          MOEGIRL_PASSWORD: ${{ secrets.MOEGIRL_PASSWORD }}
        run: |
          pnpm test
